### PR TITLE
Updated legend role colors

### PR DESCRIPTION
**Pull request by ghost**
Changed all legend role colors to Gold, Pink, Orange, Purple, Blue.

### CODE REVIEW

**Comment by brtran4** [comment]
it seems like the legend role colors are not related to config.yaml in any way. @Veraticus we should probably update this file to take the color from the config rather than hard coding it in go. ~we should also update the config.yaml file to be more consistent in colorings as there are duplicate roles with different colors for each.~ jk i didn't know we supported multiple discords

**Review by brtran4 — APPROVED** [review]

**Comment by brtran4** [comment]
created #22

**Comment by brtran4** [comment]
nit: change commit title to use the imperative voice

**Comment by ghost** [comment]
I'm closing this PR for now. I want to think about what colors more we want to choose since we don't want people getting similar color names.

**Pull request closed without merging**
